"""Analysis-plane ports; implementations only expose persisted evidence."""
from __future__ import annotations
from typing import Protocol
from analysis.domain import *
from core.provenance import TrialExecution
class CohortQueryPort(Protocol):
    def executions_for_cohort(self,cohort:CohortSnapshot)->list[TrialExecution]: ...
class AnalysisSpecificationPort(Protocol):
    def register_analysis_specification(self,spec:AnalysisSpecification)->None: ...
class AnalysisPersistencePort(Protocol):
    def create_analysis_run(self,run:AnalysisRun)->None: ...
    def finalize_analysis_run(self,run:AnalysisRun,result:AnalysisResult)->None: ...
class ArtifactStoragePort(Protocol):
    def write(self,name:str,data:bytes,media_type:str,producer_id:str,producer_version:str)->AnalysisArtifact: ...
class AnalyzerExecutionPort(Protocol):
    id:str; version:str
    def analyze(self,executions:list[TrialExecution])->dict[str,object]: ...
